### ISSUE TITLE
Integrate the new Wasm engine into the node.

### ISSUE THREAD

**Issue by abizjak** [Concordium/concordium-node#1134]
**Task description**

The current prototype has a lot of development code for testing and debugging, as well as some not-quite-right abstractions. This needs to be cleaned up.

Additionally the notion of "Artifact" that it has is different from the existing notion, so some support for migration is needed.

**Sub-tasks**

- [ ] Make sure module validation/translation operations are still adequately priced. Module translation to an artifact is slightly more complex now, but should still be cheap enough to be priced as is.
- [ ] Investigate remaining low-level optimisations (e.g., how data is read from buffers)
- [ ] polish the new engine to a production ready one
- [ ] integrate it into the node, taking care of migration for existing artifacts
