### ISSUE TITLE
Windows node distribution

### ISSUE THREAD

**Issue by td202** [Concordium/concordium-node#118]
**Task description**

Provide a distribution of the node for Windows.
This includes a service wrapper that will run as a background service and start and monitor nodes.

**Sub-tasks**
- [ ] A service wrapper for running nodes based on a configuration file, running as a Windows service.
- [ ] Shortcuts for starting, stopping and configuring nodes.
- [ ] An installer/uninstaller.
- [ ] A pipeline for reproducible, automatic builds on Windows.
