### ISSUE TITLE
Revise GRPC APIs to account for protocol updates

### ISSUE THREAD

**Issue by td202** [Concordium/concordium-node#136]
**Task description**

The current GRPC APIs do not expose information about protocol updates that have occurred. They should be revised accordingly.

**Sub-tasks**
- [ ] Identify what should be exposed and how.
- [ ] Implement the change in the node.
- [ ] Update dependent components as necessary.

**Comment by td202** [comment]
Comments from @abizjak:

`GetConsensusStatus`:

> Which [best block] height will be returned here, from genesis or from last update?

> I think the current protocol version (and I suppose the regenesis index as well) should be included in consensus status. It should also include the current genesis hash and if heights are from the last genesis then it would be useful to have the total height of the chain until the update.
>
>This should be included in the changelog, but since it's JSON adding this to the status should not be a breaking change.

`GetBlocksAtHeight`:

> What is the meaning of height here? Is it from last genesis?
>
> I think this endpoint is a lot more useful if heights are from genesis.

`GetBlockInfo`:

> Is this going to be the height since last genesis?
>
> While I think this is useful, it is also useful to know the height since actual genesis, which should also be available.

Currently, all of the above are treated as with respect to the most recent (re)genesis.

A couple of alternatives for handling height:

* Convert between regenesis-relative height (used everywhere internally) and absolute height for external queries.
* Use a pair of (genesis index, regenesis-relative height) to specify the height of a block over the whole multi-chain.

I generally prefer the second, since I'm worried that relative and absolute height could get confused in some contexts, but I can see that absolute height may be a more intuitive concept.

**Comment by abizjak** [comment]
This has been completed by #148 and partly by #141
