### ISSUE TITLE
Remove support for legacy wire protocol

### ISSUE THREAD

**Issue by td202** [Concordium/concordium-node#190]
**Task description**

Node version 1.1.x introduced a new wire protocol (version 1), while maintaining support for the old one (version 0) used by version 1.0.x peers. Since the protocol update is now effective on all our networks, there is no need to retain support for the version 0 wire protocol. This means that the compatibility shim can be removed.

**Sub-tasks**
- [ ] Disallow connections from peers that only support wire protocol version 0
- [ ] (Optional) disallow connections from v1.0.x peers. (Optional, since they will be disallowed by the wire protocol version implicitly.)
- [ ] Remove wire protocol shim
