### ISSUE TITLE
Stake Delegation

### ISSUE THREAD

**Issue by td202** [Concordium/concordium-node#212]
**Task description**

This task is to implement the Sirius stake delegation proposal in the node. This allows accounts to lock up (part of) their capital and delegate it to a nominated baker (contributing to the stake of that baker) or to a common pool (which does not affect the relative stake of bakers). By delegating their stake, accounts earn interest as a share of the rewards derived from minting and transaction fees.

**Sub-tasks**
- [x] New protocol version
- [x] Chain parameters
- [x] State
  - [x] Account
  - [x] Bakers/BirkParameters
- [x] Chain parameter updates
- [x] Transaction payloads
- [x] Payday implementation
- [x] Transaction handling
- [x] Protocol update

**Comment by td202** [comment]
### Immediate tasks

This is a list of next steps (at the time of writing).

#### Processing of update queueus

- [ ] The update queue implementations have some missing cases for new parameters. These should be added.

- [ ] Changes to the commission rate ranges should update the commission rates for bakers so that they fall within these bounds. (Possibly this will need to wait until we have revised the bakers state.)

#### Handling of ConfigureBaker and ConfigureDelegation transactions

- [ ] These should be implemented. Some changes/additions will be needed once we have revised the bakers state, but we can make a start. Possibly, missing functionality from the bakers state can be stubbed out where appropriate.

#### Changes to parameters

- [ ] In line with discussions, we should switch to mintPerPayday. This should (probably) be part of the time parameters, rather than the mint distribution, because any change to the reward period will likely need to be combined with a change to the minting rate. This also means that the mintPerSlot should be removed in ChainParametersV1, and we will probably have separate V0 and V1 update payloads for MintDistribution.

#### concordium-client

- [ ] Complete the implementation of the baker/delegation configuration.

- [ ] Support for the new/changed chain parameters.

#### genesis tool (concordium-base)

- [ ] Fix for new genesis data version

#### Changes to baker state

- [ ] The baker state should be updated to account for the new stakes that bakers have under the delegation scheme.

**Comment by andreaslyn** [comment]
Handling of ConfigureBaker and ConfigureDelegation transactions has mostly been implemented, but before we can tick it off we need to handle the following scenarios:
* When a baker changes "open for delegation status", such that the existing delegators need to be removed.
* Disallow overdelegation to a pool. Two cases when configuring delegator:
  * The delegator adds/increases staked amount and makes the pool's total staked amount "too large".
  * The total amount of delegated stake is too large in comparison to the pools owner's stake.

**Comment by abizjak** [comment]
Closed by #253
