### ISSUE TITLE
Synchronous contract calls: Node support

### ISSUE THREAD

**Issue by abizjak** [Concordium/concordium-node#236]
**Task description**

Implement V1 contracts that use synchronous function calls instead of actions for inter-contract communication, as well as for other operations, such as transfers from a contract to account.

The high-level requirements are
- smart contracts can invoke other smart contracts in the middle of their execution, in a synchronous way, and inspect the return value.
- the node API must be extended so that smart contracts may be invoked locally without transactions to obtain parts of contract state, or to dry run a contract call.
- existing contracts must continue to function as they did in current protocol versions.
- As usual, all changes must be fully backwards compatible. The node must be able to process all existing blocks, and either migrate existing database, or use it as is.

NB: V1 contracts will also have the new state. However we will implement this in steps, first sync calls and then add the new state, so that changes are more manageable.

**Sub-tasks**
- [x] Introduce V1 contract modules and contract instances. Contract modules will need to have a different version since they need to be validated differently, due to the different host functions available. The type of the contract is determined by the module which contains its functions.
  - [x] Introduce support for V1 and V0 modules and contract instances in global state.
  - [x] Introduce support for handling V1 modules and contract updates in the Scheduler. It must be possible to send messages from V0 contracts to V1 contracts, and invoke V0 contracts from V1 contracts. Existing transactions will be used to initialize and update both V0 and V1 contracts.
  - [x] Add unit tests with example contracts.
- [x] Add a new API endpoint "InvokeContract" that invokes a contract and returns the response. The invocation should take any parameters necessary. In particular it should take a block as an argument and it should execute the contract in the state at the end of the given block. In the future we can make this more fine-grained and execute it in the state in the middle of a block, however this should not be in the first version.
- [x] Add documentation of the new API endpoint.
- [x] Add documentation of the contract calling semantics, and the API the smart contracts expect.

This requires a new protocol version. Some of the changes are therefore going to be dependent, or conflict with, work being done on the #212 issue. We'll have to resolve those when they arrive.

**Comment by abizjak** [comment]
Addressed in #243
