### ISSUE TITLE
Faster catchup

### ISSUE THREAD

**Issue by abizjak** [Concordium/concordium-node#371]
Catchup time for the node grows longer every day. Long term we need light nodes or similar that do not require the entire history. In the meantime we can do some relatively easy improvements that will increase catchup speed by a factor of 2 or more in the common case.

Some of these are
- [ ] (7) Add out of band catchup to node (including sensible defaults to distributions).
   Currently out of band catchup works by the user downloading the catchup file, and then starting the node with the `--import-blocks-from` flag. The first improvement here is to make the node download the file from the given URL instead of a file name.
This will then open up for the task below where the node will only download partial files based on what information it already has.
- [ ] (3) split out of band into smallish timeslot files instead of one large file.
- [ ] (10) Research any other ways to improve catchup time that are purely engineering improvements without requiring extensive network upgrades.
  - optionally disable certain signature checks (and, thus, loosen security)?
  - batch together LMDB writes to reduce the number of fsync() calls?

# Acceptance criteria

The out-of-band catch-up time is decreased by 50% on mainnet.
