### ISSUE TITLE
Implement the new grpc API in the node

### ISSUE THREAD

**Issue by abizjak** [Concordium/concordium-node#433]
**Task description**

Depends on
- #431 
- #432 (likely to be done in combination with it)

This task covers the implementation of the new API on the node.

This API should be exposed in addition to the existing one, and the node runner should be able to choose which one (or none or both) to run for the time being.
## Consensus queries
   - [x] GetAccountList
   - [x] GetAccountInfo
   - [x] GetInstanceList
   - [x] GetInstanceInfo
   - [x] GetAncestors
   - [x] GetModuleSource
   - [x] GetModuleList
   - [x] GetFinalizedBlocks
   - [x] GetNextAccountNonce
   - [x] GetConsensusInfo
   - [x] GetCryptographicParameters
   - [x] InvokeContract
   - [x] GetBlockInfo
   - [x] GetBakerList
   - [x] GetPoolStatus
   - [x] GetDelegators
   - [x] GetTokenomicsStatus
   - [x] GetBlocksAtHeight
   - [x] SendTransaction
      - [x] Header fully typed
      - The response should be the transaction hash.
      - For payloads we want to first model the common ones and have an extra
        "other" payload which just takes a serialized transaction payload. (More can be added later)
      The following should be modelled.
          - [x] Transfer (with and without memo)
          - [x] DeployModule
          - [x] InitContract
          - [x] UpdateContract
          - [x] RegisterData
   - [x] GetTransactionStatus
   - [x] GetBranches
   - [x] GetBirkParameters
   - [x] GetIdentityProviders
   - [x] GetAnonymityRevokers
   - [x] GetAccountNonFinalizedTransactions
   - [ ] GetBlockTransactions
   - [x] GetBlockEvents
   - [ ] GetPendingUpdates
   - [ ] GetChainParameters
   - [x] GetBlocks
   - [ ] Split `types.proto` into multiple files to help the compilers out (the generated file is quite large).
   
## Node queries   
   - [x] PeerConnect
   - [x] PeerDisconnect
   - [x] GetNodeStatus
   - [x] GetPeersInfo
   - [x] DumpStop
   - [x] DumpStart
   - [x] BanNode
   - [x] UnbanNode
   - [x] GetBannedPeers
   - [x] Shutdown
