### ISSUE TITLE
Set up GRPC2 approach

### ISSUE THREAD

**Issue by abizjak** [Concordium/concordium-node#475]
**Task description**

This task is part of https://github.com/Concordium/concordium-node/issues/433 
The scope of this task is to set up the infrastructure needed to implement all the endpoints. This is slightly non-trivial due to the use of Haskell and Rust, and the fact that the RPC server is in Rust, but the data mostly lives in the Haskell part of the codebase.

Since this infrastructure requires quite a bit of setup this is a separate task so it may be reviewed more easily.

**Sub-tasks**
- [x] Set up node configuration to support the new API.
- [x] Add support for grpc-web
- [x] Add support for endpoint configuration, in particular enabling/disabling different endpoints via node configuration options.
- [x] Implement some endpoints, enough to demonstrate and show feasibility of the approach.
