### ISSUE TITLE
Account structure revision

### ISSUE THREAD

**Issue by td202** [Concordium/concordium-node#523]
Revise the structure of accounts to better optimise for storage and updating. [Feature proposal.](https://concordium.atlassian.net/wiki/spaces/EN/pages/1031798792/Account+Structure+Revision)

- [x] Remove redundant credential map from account table.
- [x] Refactor to support `AccountV2`.
- [ ] Revise high-level storage and hashing of accounts.
- [ ] Revise hashing and storage of release schedules.
- [ ] Revise top level release schedule map.
- [ ] Avoid unnecessary use and look-up of account addresses.
- [ ] Implement migration from `AccountV1` to `AccountV2` for protocol update.
