### ISSUE TITLE
Implement chain queries from smart contracts.

### ISSUE THREAD

**Issue by abizjak** [Concordium/concordium-node#562]
**Task description**

This task is for the on-chain parts of chain queries.
As specified in the #556 epic 

There should be three new operations to invoke
- accountBalance that takes an account address and returns staked balance and total public balance
- contractBalance that takes a contract address and returns the balance owned by the contract
- exchangeRate that returns CCD/EUR and EUR/NRG exchange rates (as 4 64-bit integers).

All of these should only be enabled on P5 and up, and only for V1 contracts.

**Sub-tasks**
- [ ] Add the new events to the grpc-api.
- [ ] Add new events to the list of possible contract events.
- [ ] Update the GRPC2 API with new events.
- [x] Implement the new operations in the smart contract execution engine.
- [x] Implement the new queries in the scheduler/the node.
- [ ] Update the Rust SDK with the new events.
- [x] Unit tests.

**Comment by limemloh** [comment]
It was decided that a chain query from a smart contract, will not produce an event, meaning no changes needed for the gRPC and SDKs.
