### ISSUE TITLE
Implement relaxed resource restrictions.

### ISSUE THREAD

**Issue by abizjak** [Concordium/concordium-node#563]
**Task description**

As part of #530 we agreed to do the following for protocol version 5
- [x] Parameter size is maximum practical, that is 65kB (maximum length representable by u16)
- [x] Return value is unbounded apart from limit imposed by serialization
- [x] Number of logs is u32::MAX now.

This affects
- [x] The node/scheduler
- [x] Smart contract execution engine
- [x] Cargo-concordium.  https://github.com/Concordium/concordium-smart-contract-tools/pull/12
- [x] concordium-std if it checks limits, or has constants for limits. (There were no limits)
- [x] Tools which might check these limits (concordium-client, Rust SDK).
  - [x] concordium-client https://github.com/Concordium/concordium-client/pull/181
  - [x] Rust SDK https://github.com/Concordium/concordium-rust-sdk/pull/57
