### ISSUE TITLE
Upgrade compiler tooling and libraries.

### ISSUE THREAD

**Issue by vikt0r0** [Concordium/concordium-node#648]
**Task description**
Upgrade stackage snapshot to `lts-20.4` (with ghc 9.2.5) as well as some libraries. The relevant library dependencies are:

- `haskell-lmdb` which is our own fork as the repository is unmaintained,
- `flatbuffers` since there is a security advisory in the version we currently use.

The relevant repositories in which to upgrade the tooling are `Concordium/`

- `concordium-base`,
- `concordium-node`,
- `concordium-client`,
- `concordium-wallet-proxy`,
- `tokenomics-reporter`,
- `http2-client`
- `http2-grpc-haskell` and
- `haskell-lmdb`

**Sub-tasks**
Upgrade compiler tooling, fix errors and warnings in:
- [x] `concordium-base`,
- [x] `concordium-node`,
- [x] `concordium-client`,
- [x] `concordium-wallet-proxy`,
- [x] `http2-client`,
- [x] `http2-grpc-haskell` and
- [x] `tokenomics-reporter`

Libraries:
- [x] Upgrade `flatbuffers` dependencies ~where applicable~ in `concordium-node` (figure out if there are other places?).
- [x] Upgrade `haskell-lmdb` to latest version where applicable (figure out where?).

Other:
- [x] Install and use appropriate `flatc` binary in build jobs.

Node build jobs:
- [x] concordium-node-ubuntu
- [x] concordium-node-macos
- [x] concordium-node-windows

Client build jobs:
- [x] distribution-concordium-client-linux
- [x] distribution-concordium-client-macos
- [x] distribution-concordium-client-windows

Other build jobs:
- [x] concordium-database-exporter
- [x] tokenomics-reporter
- [x] wallet-proxy
- [x] distribution-image-docker
- [x] docker-image-base
- [x] docker-image-static-libraries

Note that the estimate for this task highly depends on the number of altered/deprecated API's when updating the compiler tooling.
