### ISSUE TITLE
Review hashing schemes and domain separation

### ISSUE THREAD

**Issue by eb-concordium** [Concordium/concordium-node#722]
**Task description**
This task is to check a few things regarding hashing schemes and domain separation. This is about some of the functions in concordium-node/concordium-consensus/src/Concordium/Konsensus/V1/Types.hs.

**Sub-tasks**
- [ ] Determine if the hashing scheme used in `computeTransactionsHash` is appropriate.
- [ ] Check that the messages bytes in `quorumSignatureMessageBytes` cannot collide with other signed messages.
- [ ] Check that the messages bytes in `timeoutSignatureMessageBytes` cannot collide with other signed messages.
- [ ] Determine if domain seperators should be used in `blockSignatureMessageBytes`.
