### ISSUE TITLE
MS 2 New Consensus: Tasks For Next Milestone

### ISSUE THREAD

**Issue by EmilLa1** [Concordium/concordium-node#739]
The following tasks should be addressed in the next milestone: 

- [x] Finalization committee selection https://github.com/Concordium/concordium-node/issues/730
- [x] Consensus <> Scheduler https://github.com/Concordium/concordium-node/issues/699
- [x] Consensus <> P2P https://github.com/Concordium/concordium-node/issues/700
- [x] Genesis generation tool
- [x] Concordium std update https://github.com/Concordium/concordium-rust-smart-contracts/pull/280
