### ISSUE TITLE
Improve sandboxing of the debian package

### ISSUE THREAD

**Issue by abizjak** [Concordium/concordium-node#74]
**Task description**

The debian package uses systemd to manage the node and the collector. The collector is effectively sandboxed, it does not have write access to anywhere, and runs with `DynamicUser` as well.

The node service is also heavily sandboxed, it only has read access to most of the system, and limited system call availability, but it still runs as root.

The node only needs read and write access to its config & data directories. We should

- [x] run the service with DynamicUser=yes
- [x] have config & data directories specified with StateDirectory (or similar flags if we need to set the current working directory)
- [x] make sure to update instructions on how to become a baker. With sandboxing it is important to make sure the node can read its keys on start. Perhaps using ConfigurationDirectory to specify that makes sense.
