### ISSUE TITLE
New Consensus: GRPC changes

### ISSUE THREAD

**Issue by EmilLa1** [Concordium/concordium-node#857]
- [x] Clean up the FIXME's in the `Queries.hs` module.  https://github.com/Concordium/concordium-node/issues/870
- [x] Test (introduce raw support in the client)
- [x] Make tasks for new queries that should be implemented in the near future.
- https://github.com/Concordium/concordium-node/issues/871
- https://github.com/Concordium/concordium-node/issues/872
- https://github.com/Concordium/concordium-node/issues/873
- https://github.com/Concordium/concordium-node/issues/874
- https://github.com/Concordium/concordium-node/issues/996
- [ ] Make tasks the remaining SDKs. (Rust, JS, .NET, Java)

**Comment by tschudid** [comment]
For tokenomics testing the following queries would be of interest: 

- Get PoolParameters for the current reward period (e.g. the baking commission range).
- Get the payout block for reward period `n`. Or more generally, get the first block of an epoch.

**Comment by td202** [comment]
>     * Get PoolParameters for the current reward period (e.g. the baking commission range).

The PoolParameters are not snapshotted. (Rather, the commission rates on each baker are. Currently, these are not exposed by GetPoolInfo, but possibly should be.) I think it doesn't make much sense to implement this in the node.

>     * Get the payout block for reward period `n`. Or more generally, get the first block of an epoch.

I think we can add getting the first block of an epoch to the API.
