### ISSUE TITLE
Implement trivial protocol update P6 -> P6

### ISSUE THREAD

**Issue by eb-concordium** [Concordium/concordium-node#932]
**Task description**
Implement the protocol update from P6 to P6.

**Sub-tasks**
- [ ] Add P6 folder with a trivial update P6->P6 in it.
- [ ] Add P6 module (with a hash and a `updateRegenesis` function)
- [ ] Support new protocols in `checkForProtocolUpdateV1`, and recognize the P6->P6 update.
