### ISSUE TITLE
Do not start V1 API on startup, and in distributions.

### ISSUE THREAD

**Issue by abizjak** [Concordium/concordium-node#936]
**Task description**

Currently GRPC V1 API is started by default both by the node itself, and it is configured to do so also in all distributions.

In order to pave the way for deprecation we will first disable it in all distributions.

- [x] Do not start GRPC V1 API unless explicitly configured.
- [x] Do not start it in distributions
- [x] Update example docker-compose files (also in documentation) to remove V1 configuration.
